/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as KarseellRouteImport } from './routes/karseell'
import { Route as FunnelRouteImport } from './routes/funnel'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorIndexRouteImport } from './routes/advisor.index'
import { Route as AdvisorThreadIdRouteImport } from './routes/advisor.$threadId'

const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const KarseellRoute = KarseellRouteImport.update({
  id: '/karseell',
  path: '/karseell',
  getParentRoute: () => rootRouteImport,
} as any)
const FunnelRoute = FunnelRouteImport.update({
  id: '/funnel',
  path: '/funnel',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorIndexRoute = AdvisorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdvisorRoute,
} as any)
const AdvisorThreadIdRoute = AdvisorThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AdvisorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/finance': typeof FinanceRoute
  '/funnel': typeof FunnelRoute
  '/integrations': typeof IntegrationsRoute
  '/karseell': typeof KarseellRoute
  '/planner': typeof PlannerRoute
  '/advisor/$threadId': typeof AdvisorThreadIdRoute
  '/advisor/': typeof AdvisorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/finance': typeof FinanceRoute
  '/funnel': typeof FunnelRoute
  '/integrations': typeof IntegrationsRoute
  '/karseell': typeof KarseellRoute
  '/planner': typeof PlannerRoute
  '/advisor/$threadId': typeof AdvisorThreadIdRoute
  '/advisor': typeof AdvisorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/finance': typeof FinanceRoute
  '/funnel': typeof FunnelRoute
  '/integrations': typeof IntegrationsRoute
  '/karseell': typeof KarseellRoute
  '/planner': typeof PlannerRoute
  '/advisor/$threadId': typeof AdvisorThreadIdRoute
  '/advisor/': typeof AdvisorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/campaigns'
    | '/finance'
    | '/funnel'
    | '/integrations'
    | '/karseell'
    | '/planner'
    | '/advisor/$threadId'
    | '/advisor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns'
    | '/finance'
    | '/funnel'
    | '/integrations'
    | '/karseell'
    | '/planner'
    | '/advisor/$threadId'
    | '/advisor'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/campaigns'
    | '/finance'
    | '/funnel'
    | '/integrations'
    | '/karseell'
    | '/planner'
    | '/advisor/$threadId'
    | '/advisor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRouteWithChildren
  CampaignsRoute: typeof CampaignsRoute
  FinanceRoute: typeof FinanceRoute
  FunnelRoute: typeof FunnelRoute
  IntegrationsRoute: typeof IntegrationsRoute
  KarseellRoute: typeof KarseellRoute
  PlannerRoute: typeof PlannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karseell': {
      id: '/karseell'
      path: '/karseell'
      fullPath: '/karseell'
      preLoaderRoute: typeof KarseellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funnel': {
      id: '/funnel'
      path: '/funnel'
      fullPath: '/funnel'
      preLoaderRoute: typeof FunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/': {
      id: '/advisor/'
      path: '/'
      fullPath: '/advisor/'
      preLoaderRoute: typeof AdvisorIndexRouteImport
      parentRoute: typeof AdvisorRoute
    }
    '/advisor/$threadId': {
      id: '/advisor/$threadId'
      path: '/$threadId'
      fullPath: '/advisor/$threadId'
      preLoaderRoute: typeof AdvisorThreadIdRouteImport
      parentRoute: typeof AdvisorRoute
    }
  }
}

interface AdvisorRouteChildren {
  AdvisorThreadIdRoute: typeof AdvisorThreadIdRoute
  AdvisorIndexRoute: typeof AdvisorIndexRoute
}

const AdvisorRouteChildren: AdvisorRouteChildren = {
  AdvisorThreadIdRoute: AdvisorThreadIdRoute,
  AdvisorIndexRoute: AdvisorIndexRoute,
}

const AdvisorRouteWithChildren =
  AdvisorRoute._addFileChildren(AdvisorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRouteWithChildren,
  CampaignsRoute: CampaignsRoute,
  FinanceRoute: FinanceRoute,
  FunnelRoute: FunnelRoute,
  IntegrationsRoute: IntegrationsRoute,
  KarseellRoute: KarseellRoute,
  PlannerRoute: PlannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
